env:
  CARGO_HOME: ${HOME}/.cargo
  PATH: ${PATH}:${CARGO_HOME}/bin # for rustup

linux_task:
  env:
    TARGET: x86_64-unknown-linux-musl
  container:
    image: debian:buster-20191118-slim
  install_script:
    - apt-get -qqq update
    - apt-get -qqq install clang curl libclang-dev llvm libgmp-dev nettle-dev pkg-config
    - apt-get -qqq install gpg # test_script requirement
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable-${TARGET} -y
    - source ${CARGO_HOME}/env
    - cargo version
  cargo_cache: &cargo_cache
    folder: ${CARGO_HOME}/registry
    fingerprint_script: cat Cargo.lock
  check_script: &check_script
    - cargo fmt -- --check
  test_script: &test_script
    - RUST_BACKTRACE=1 cargo test
  build_script: &build_script
    - cargo build --bins --release --target ${TARGET}
  before_cache_script: &before_cache_script
    - rm -rf ${CARGO_HOME}/registry/index
  binaries_artifacts: &binaries_artifacts
    path: "target/release/keygen"

macos_task:
  env:
    TARGET: x86_64-apple-darwin
  matrix:
    osx_instance:
      image: mojave-xcode
  install_script:
    - curl https://sh.rustup.rs -sSf | sh -s -- -y # installs default profile, default toolchain
    - brew install libnettle llvm # present: gmp pkg-config
    - brew install gpg # test_script requirement
  cargo_cache: *cargo_cache
  check_script: *check_script
  test_script: *test_script
  build_script: *build_script
  before_cache_script: *before_cache_script
  binaries_artifacts: *binaries_artifacts
