language: rust
addons:
  apt:
    - clang
    - libclang-dev
    - libgmp-dev
    - nettle-dev
    - pkg-config
  homebrew:
    - gmp
    - libnettle
    - pkg-config
script: cargo test

# Test all supported Rust versions on Linux. On macOS, test against Rust stable
# only to save time.
jobs:
  include:
    # Linux
    - rust: 1.33.0
    - rust: stable
    - rust: beta
    - rust: nightly
    # macOS
    - rust: stable
      os: osx
