language: rust
before_install: sudo apt-get update
install: sudo apt-get install clang libclang-dev libgmp-dev nettle-dev pkg-config
script: cargo test

# Test all supported Rust versions on Linux. On macOS, test against Rust stable
# only to save time.
jobs:
  include:
    # Linux
    - rust: 1.33.0
    - rust: stable
    - rust: beta
    - rust: nightly
    # macOS
    - rust: stable
      os: osx
