language: rust

script: cargo test

# Test all supported Rust versions on Linux. On macOS, test against Rust stable
# only to save time.
jobs:
  include:
    # Linux
    - rust: 1.34.0
      addons: &apt_addons
        apt:
          packages:
            - clang
            - libclang-dev
            - libgmp-dev
            - nettle-dev
            - pkg-config
    - rust: stable
      addons: *apt_addons
    - rust: beta
      addons: *apt_addons
    - rust: nightly
      addons: *apt_addons
    # macOS
    - rust: stable
      os: osx
      addons:
        homebrew:
          packages:
            - gmp
            - libnettle
            - pkg-config
